const express = require('express')
const router = express.Router()
const usuarioController = require('../controllers/usuario.controller')

router.get('/usuarios', usuarioController.getUsers)
router.get('/usuarios/:id', usuarioController.getUserById)
router.post('/regitro', usuarioController.registro)
router.post('/login', usuarioController.login)
router.put('/usuarios/:id', usuarioController.updateUser)
router.delete('/usuarios/:id', usuarioController.deactivateUser)
router.get('/confirm-usuario/:token', usuarioController.confirmUser)
router.put('/activar-usuario/:id', usuarioController.activateUser)
router.get('/perfil', usuarioController.getPerfil)
router.get('/saldo', usuarioController.getSaldo)
router.put('/saldo', usuarioController.updateSaldo)
router.put('/cambiar-password', usuarioController.cambiarPassword)
router.put('/cambiar-email', usuarioController.cambiarEmail)
router.get('/confirm-email/:token', usuarioController.confirmEmail)
router.get('/active-usuarios', usuarioController.getActiveUsers)
router.get('/saldo-usuario/:id', usuarioController.getSaldoUsuario)

module.exports = router
